name: Main
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Verify
        run: npm run verify
      - name: Build
        run: npm run generate
      - name: Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name casachristinaproduction --source '$web' --connection-string="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
            az storage blob upload-batch --account-name casachristinaproduction --source .output/public --destination '$web' --connection-string="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
      - name: Purge CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APPLICATION_ID }} --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT_ID }} --allow-no-subscriptions
            az cdn endpoint purge --content-paths '/*' --resource-group casa-christina-production --profile-name casachristina-cdn --name casachristina
