name: Main
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Verify
        run: npm run verify
      - name: Build
        run: npm run build
      - name: Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch \
            --account-name casachristinaproduction \
            --source '$web' \
            --connection-string="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
            az storage blob upload-batch \
            --account-name casachristinaproduction \
            --destination '$web' \
            --source home/.vitepress/dist \
            --connection-string="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"