name: Main
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.11
      volumes:
        - dist:/__w/cc-homepage/cc-homepage/home/.vitepress/dist
        - temp:/__w/cc-homepage/cc-homepage/home/.vitepress/temp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
