name: Main
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.11
    steps:
      - name: Clone
        run: git clone --depth 1 git@github.com:NiklausMaurer/cc-homepage.git .
      - name: Build
        run: npm run build
