name: Main
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.11
      volumes:
        - dist:~/.vitepress/dist
        - temp:~/.vitepress/temp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Prepare Build
      - name: Build
        run: npm run build
