name: Main
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18.11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: npm run build
